"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require('express');
var cookieParser = require('cookie-parser');
var cors = require('cors');
var express_validator_1 = require("express-validator");
var database_service_1 = require("./src/Services/database.service");
var authRoutes_1 = require("./src/Routes/authRoutes");
var categoryRoute_1 = require("./src/Routes/categoryRoute");
var productRoute_1 = require("./src/Routes/productRoute");
var bodyParser = require("body-parser");
var dotenv = require('dotenv');
dotenv.config();
var url = process.env.MONGO_uri;
(0, database_service_1.connectToDatabase)();
var PORT = process.env.PORT;
var logger = require('pino')();
var app = express();
app.use(bodyParser.json());
app.use(express.urlencoded({ extended: false }));
app.use(cors());
app.use(cookieParser());
app.use((0, express_validator_1.query)());
app.use("/api/user", authRoutes_1.default);
app.use("/api/category", categoryRoute_1.default);
app.use("/api/product", productRoute_1.default);
var server = app.listen(PORT, function () {
    console.log("App is listening on port ".concat(PORT));
    logger.info("App has started");
});
exports.default = server;
